### ISSUE TITLE
Error running command bin/magento m2bp:critical-css:generate 

### ISSUE THREAD

**Issue by JelleGe** [m2-boilerplate/Module-Critical-CSS#5]
We face the following issue when we run the command `bin/magento m2bp:critical-css:generate `

```
The command "'critical' '--version'" failed.                             
                                                                           
  Exit Code: 127(Command not found)                                        
                                                                           
  Working directory: /application  
                                                                           
  Output:                                                                  
  ================                                                         
                                        
  Error Output:                                                            
  ================                                                         
  sh: regel 0: exec: critical: not found                               
                                                                           

m2bp:critical-css:generate
```

**Comment by thampe** [comment]
Hi,

did you install the critical npm package?

```
npm i -D critical

**Comment by JelleGe** [comment]
Thanks! That indeed solved the issue. We now face some other issue, when running: `bin/magento m2bp:critical-css:generate`

`The command "'critical' 'https://domain.com/customer/account/login/' '--dimensions' '375x812' '--dimensions' '576x1152' '--dimensions' '768x1024' '--dimensions' '1024x768' '--dimensions' '1280x720'" failed.  Exit Code: 1(General error)  Working directory: /application  Output: ================   Error Output: ================    Error: Failed to launch the browser process!    /node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory      TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md      Usage: critical <input> [<option>]     Options:      -b, --base              Your base directory      -c, --css               Your CSS Files (optional)      -w, --width             Viewport width      -h, --height            Viewport height      -i, --inline            Generate the HTML with inlined critical-path CSS      -e, --extract           Extract inlined styles from referenced stylesheets       --inlineImages          Inline images      --dimensioms            Pass dimensions e.g. 1300x900      --ignore                RegExp, @type or selector to ignore      --ignore-[OPTION]       Pass options to postcss-discard. See https://goo.gl/HGo5YV      --include               RegExp, @type or selector to include      --include-[OPTION]      Pass options to inline-critical. See https://goo.gl/w6SHJM      --assetPaths            Directories/Urls where the inliner should start looking for assets.      --user                  RFC2617 basic authorization user      --pass                  RFC2617 basic authorization password      --penthouse-[OPTION]    Pass options to penthouse. See https://goo.gl/PQ5HLL      --ua, --userAgent       User agent to use when fetching remote src `
