### ISSUE TITLE
There are no commands defined in the "m2bp:critical-css" namespace.

### ISSUE THREAD

**Issue by alexsmith2709** [m2-boilerplate/Module-Critical-CSS#6]
After installing and enabling when i run the command "php bin/magento m2bp:critical-css:generate" i get the error "There are no commands defined in the "m2bp:critical-css" namespace." 
I have checked "php bin/magento list" and there is no m2bp listed there.
I am using magento 2.3.6 and PHP 7.3. Critical was installed before this module by running "npm i -D critical"

**Comment by thampe** [comment]
Hi,

did you enable the module first?

```
bin/magento module:enable M2Boilerplate_CriticalCss
bin/magento setup:upgrade
```

**Comment by alexsmith2709** [comment]
Yes, the module is enabled. This was something i thought of and checked,

**Comment by marvinhinz** [comment]
> Yes, the module is enabled. This was something i thought of and checked,

Is the issue still relevant, or could you resolve the problem?
