### ISSUE TITLE
Problem with multiple store views - Argument 1 passed to M2Boilerplate\CriticalCss\Service\CriticalCss::createCriticalCssProcess() must be of the type string, null given

### ISSUE THREAD

**Issue by jg-development** [m2-boilerplate/Module-Critical-CSS#7]
Uncaught TypeError: Argument 1 passed to M2Boilerplate\CriticalCss\Service\CriticalCss::createCriticalCssProcess() must be of the type string, null given

The problem is caused by a cms page only for one store view (only german, not english).
So the url for the english store is null.

[en:cms_page|23] - https://xxx/de/widerrufsformular
[en:cms_page|24] 

The CmsPageProvider uses the main "0" and given store id (like "2"), but does not check if the url for the given store view is active/set.

**Comment by thampe** [comment]
Hi, 

thanks for reporting this issue. Could you check if the current master branch has fixed it?

I will create a new release afterwards.

**Comment by jg-development** [comment]
thx ... I will check it this in the next few days

**Comment by thampe** [comment]
Closed due to lack of feedback.

**Comment by jg-development** [comment]
sry .... I am currently under heavy workload .... will try to test it soon

**Comment by jg-development** [comment]
but from code review it looks good for me
