### ISSUE TITLE
Inline Critical CSS showing wrong font path when not in root path. 

### ISSUE THREAD

**Issue by enyceedanny** [m2-boilerplate/Module-Critical-CSS#8]
When in homepage or any page that isn't a "sub-directory", the path in the inline CSS is fine, but when inside a path such as "https://example.com/category/product", the path for the font becomes "https://example.com/category/product/pub/static/version1234567/frontend/vendor/theme/en_US/fonts/font.woff2"

**Comment by thampe** [comment]
Hi,

thanks for reporting the issue. Could you try the latest release (`1.0.2`) and see if it is fixed?
