### ISSUE TITLE
Missing argument

### ISSUE THREAD

**Issue by torhoehn** [m2-boilerplate/Module-Critical-CSS#9]
While running `bin/magento m2bp:critical-css:generate` I get the following error:

```
In AbstractFactory.php line 238:

  Missing required argument $commandline of Symfony\Component\Process\Process.
```

I already configured the path (`dev/css/critical_css_critical_binary`) to `/home/<user>/.npm-global/bin/critical`.

**Comment by thampe** [comment]
Hi,

did you do a ` setup:di:compile` and `cache:clear` after the installation?

**Comment by torhoehn** [comment]
Yes and I also receive this error in developer mode.

**Comment by thampe** [comment]
Which Magento Version do you have?

**Comment by torhoehn** [comment]
Magento 2.3.3

**Comment by thampe** [comment]
Hi,

could you test the changes from my PR #10? 

This error seems to be due to a change in the symfony process library. If everythings works fine I will merge it and release a new version.

Thanks!

**Comment by torhoehn** [comment]
Just found out what the problem is:
magento/framework requires symfony/process (~4.1.0).
With the release of symfony/process 4.2 the constructor argument was renamed to command (before it was commandline).

**Comment by torhoehn** [comment]
@thampe Okay. I'll test your PR. :D

**Comment by thampe** [comment]
Hi,

a release is out now, that includes the fix.

Thanks for pointing out the issue!
